name: Code Quality

on: workflow_call

jobs:
  rector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP Environment
        uses: ./.github/actions/setup-php

      - name: Automated Refactoring - Rector
        run: composer run-script rector-check

  phpstan:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v4
       
     - name: Setup PHP Environment
       uses: ./.github/actions/setup-php

     - name: Check Code Analysis - PHPStan
       run: composer run-script phpstan
