name: Lint

on: workflow_call

jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Pint
        run: composer run-script pint-check
