on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP Environment
        uses: ./.github/actions/setup-php

  lint:
    needs: build
    uses: ./.github/workflows/lint.yml

  code-quality:
    needs: build
    uses: ./.github/workflows/code-quality.yml

  security-checker:
    uses: ./.github/workflows/security.yml
